// this file was generated by serverless-auto-swagger
            module.exports = {
  "swagger": "2.0",
  "info": {
    "title": "node-aws-be",
    "version": "1"
  },
  "paths": {
    "/products": {
      "get": {
        "summary": "getProductsList",
        "description": "",
        "operationId": "getProductsList.get.products",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    },
    "/products/{productId}": {
      "get": {
        "summary": "getProductById",
        "description": "",
        "operationId": "getProductById.get.products/{productId}",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "productId",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "200 response"
          }
        }
      }
    }
  },
  "definitions": {
    "Product": {
      "properties": {
        "id": {
          "title": "Product.id",
          "type": "string"
        },
        "price": {
          "title": "Product.price",
          "type": "number"
        },
        "title": {
          "title": "Product.title",
          "type": "string"
        },
        "description": {
          "title": "Product.description",
          "type": "string"
        },
        "count": {
          "title": "Product.count",
          "type": "number"
        },
        "imageUrl": {
          "title": "Product.imageUrl",
          "type": "string"
        }
      },
      "required": [
        "id",
        "price",
        "title",
        "description",
        "count",
        "imageUrl"
      ],
      "additionalProperties": false,
      "title": "Product",
      "type": "object"
    },
    "ProductsList": {
      "items": {
        "$ref": "#/definitions/Product",
        "title": "ProductsList.[]"
      },
      "title": "ProductsList.[]",
      "type": "array"
    }
  },
  "securityDefinitions": {}
};