// this file was generated by serverless-auto-swagger
module.exports = {
  swagger: "2.0",
  info: {
    title: "import-service-doc",
    version: "1",
  },
  paths: {
    "/import/{name}": {
      get: {
        summary: "importProductsFile",
        description: "",
        operationId: "importProductsFile.get.import",
        consumes: ["application/json"],
        produces: ["application/json"],
        parameters: [],
        responses: {
          200: {
            description: "200 response",
          },
        },
      },
    },
  },
  securityDefinitions: {},
};
